### ISSUE TITLE
Getting error

### ISSUE THREAD

**Issue by abhinavsagar** [naokishibuya/car-behavioral-cloning#26]
Getting-
`Using TensorFlow backend.
XXX lineno: 34, opcode: 0
Traceback (most recent call last):
  File "drive.py", line 105, in <module>
    model = load_model(args.model)
  File "C:\Users\Win 10\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "C:\Users\Win 10\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "C:\Users\Win 10\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "C:\Users\Win 10\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "C:\Users\Win 10\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\utils\generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\Users\Win 10\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\sequential.py", line 301, in from_config
    model.add(layer)
  File "C:\Users\Win 10\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\sequential.py", line 165, in add
    layer(x)
  File "C:\Users\Win 10\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\base_layer.py", line 457, in __call__
    output = self.call(inputs, **kwargs)
  File "C:\Users\Win 10\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\layers\core.py", line 687, in call
    return self.function(inputs, **arguments)
  File "model.py", line 34, in <lambda>
    model.add(Lambda(lambda x: x/127.5-1.0, input_shape=INPUT_SHAPE))
SystemError: unknown opcode`

**Comment by eriteria** [comment]
Same Here anyone please help

**Comment by PravinVedurla** [comment]
Change to python version 3.5.0

`conda install python=3.5.0`
